const add =(a,b)=>
    {
        return a+b;
    }
    console.log(add(5,3));
    
    
    
    
    const sub =(a,b)=>
    {
        return a-b;
    }
    console.log(sub(5,3));
    
    
    
    
    const mul =(a,b)=>
        {
            return a*b;
        }
        console.log(mul(5,3));
    
    
    
    
        
    const div =(a,b)=>
    {
        return a/b;
    }
    console.log(div(8,2));